// import 'package:http/http.dart' as http;
//
// Future<http.Response> fetchPost() {
//   var uri = Uri.parse('https://4a20d71c-75da-40dd-8040-6e97160527b9.mock.pstmn.io');
//   return http.get(uri);
// }
//
// class Autogenerated {
//   String status;
//   int id;
//   String nickname;
//   int questionNum;
//   int answerNum;
//   int point;
//
//   Autogenerated(
//       {this.status,
//         this.id,
//         this.nickname,
//         this.questionNum,
//         this.answerNum,
//         this.point});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     id = json['id'];
//     nickname = json['nickname'];
//     questionNum = json['question_num'];
//     answerNum = json['answer_num'];
//     point = json['point'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     data['id'] = this.id;
//     data['nickname'] = this.nickname;
//     data['question_num'] = this.questionNum;
//     data['answer_num'] = this.answerNum;
//     data['point'] = this.point;
//     return data;
//   }
// }